development:
  adapter: postgresql
  database: weather_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: weather_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: weather_production
  pool: 5
  timeout: 5000
